#!/bin/bash

# Change PICS_FOLDER value to the target folder containing the pics

cd "PICS_FOLDER"
if [ ! -d "thumbs" ]; then
  mkdir thumbs
fi
for file in *
do
  # next line checks the mime-type of the file
  IMAGE_TYPE=`file --mime-type -b "$file" | awk -F'/' '{print $1}'`
  if [ "x$IMAGE_TYPE" == "ximage" ]; then

    WIDTH=`imageinfo --width "$file"`      # obtaining the image width
    HEIGHT=`imageinfo --height "$file"`    # obtaining the image height

    # If the image width is greater that 200 or the height is greater that 150 a thumb is created
    if [ $WIDTH -ge  401 ] || [ $HEIGHT -ge 301 ]; then
       #This line convert the image in a 400 * 300 thumb 
       convert -sample 400x300 "$file" "$(dirname "$file")/thumbs/$(basename "$file")" 
    fi
  fi
done